const list = [
    { "id": 1, "title": "Biased Recommendation Algorithm", "description": "Algorithm consistently favored certain demographics, leading to skewed recommendations.", "severity": "Medium", "reported_at": "2025-03-15T10:00:00Z" },
    { "id": 2, "title": "LLM Hallucination in Critical Info", "description": "LLM provided incorrect safety procedure information, leading to potential hazards.", "severity": "High", "reported_at": "2025-04-01T14:30:00Z" },
    { "id": 3, "title": "Minor Data Leak via Chatbot", "description": "Chatbot inadvertently exposed non-sensitive user metadata, raising privacy concerns.", "severity": "Low", "reported_at": "2025-03-20T09:15:00Z" },
    { "id": 4, "title": "API Rate Limiting Issue", "description": "An API endpoint exceeded its rate limit, causing service disruptions for users.", "severity": "Medium", "reported_at": "2025-03-25T08:45:00Z" },
    { "id": 5, "title": "Unresponsive UI in Mobile App", "description": "The mobile app UI froze during interactions, leading to a poor user experience.", "severity": "Low", "reported_at": "2025-03-30T16:20:00Z" },
    { "id": 6, "title": "Unauthorized Access Attempt", "description": "Detected multiple unauthorized login attempts to a user account, raising security concerns.", "severity": "High", "reported_at": "2025-04-05T12:10:00Z" },
    { "id": 7, "title": "Data Integrity Issue in Database", "description": "An error led to inconsistent data being saved in the database, potentially affecting reports.", "severity": "High", "reported_at": "2025-04-07T11:55:00Z" },
    { "id": 8, "title": "Inaccurate Search Results", "description": "Search feature returned irrelevant results due to faulty indexing algorithms.", "severity": "Medium", "reported_at": "2025-04-03T13:40:00Z" },
    { "id": 9, "title": "UI/UX Design Flaw in Checkout Page", "description": "Users experienced confusion during the checkout process, resulting in abandoned carts.", "severity": "Medium", "reported_at": "2025-04-10T09:25:00Z" },
    { "id": 10, "title": "Faulty Data Sync Across Devices", "description": "User data failed to sync properly between mobile and web apps.", "severity": "Low", "reported_at": "2025-03-27T15:50:00Z" },
    { "id": 11, "title": "Slow Load Time for Dashboard", "description": "Dashboard takes more than 5 seconds to load, affecting user productivity.", "severity": "Medium", "reported_at": "2025-04-09T14:30:00Z" },
    { "id": 12, "title": "Broken Link in Email Notification", "description": "The link in the email notification led to a 404 error page.", "severity": "Low", "reported_at": "2025-04-02T17:45:00Z" },
    { "id": 13, "title": "Failed Payment Gateway Integration", "description": "Payment gateway failed to process a large number of transactions.", "severity": "High", "reported_at": "2025-03-28T13:10:00Z" },
    { "id": 14, "title": "Inconsistent App Behavior on iOS", "description": "App behaves unpredictably when used on iOS devices, causing crashes.", "severity": "Medium", "reported_at": "2025-03-21T11:00:00Z" },
    { "id": 15, "title": "Server Downtime During Peak Hours", "description": "Server went down during peak usage hours, impacting service availability.", "severity": "High", "reported_at": "2025-04-04T18:25:00Z" },
    { "id": 16, "title": "API Endpoint Return Empty Data", "description": "API call to a critical endpoint returned empty data, breaking functionality.", "severity": "High", "reported_at": "2025-04-06T10:15:00Z" },
    { "id": 17, "title": "Authentication Issues on Web App", "description": "Users reported difficulties logging in to the web application.", "severity": "Medium", "reported_at": "2025-03-18T12:00:00Z" },
    { "id": 18, "title": "High Latency in Video Streaming", "description": "Users experienced significant latency during video streaming.", "severity": "Medium", "reported_at": "2025-04-08T16:30:00Z" },
    { "id": 19, "title": "Data Loss After App Update", "description": "Users reported losing data after updating to the latest version of the app.", "severity": "High", "reported_at": "2025-04-11T09:40:00Z" },
    { "id": 20, "title": "Memory Leak in Mobile App", "description": "App suffered a memory leak that caused it to crash after extended usage.", "severity": "High", "reported_at": "2025-03-29T14:05:00Z" },
    { "id": 21, "title": "Broken User Profile Page", "description": "User profile page was not loading correctly, showing incomplete data.", "severity": "Low", "reported_at": "2025-04-12T10:30:00Z" },
    { "id": 22, "title": "Data Redundancy in Database", "description": "Duplicate records were found in the database, causing confusion in reports.", "severity": "Medium", "reported_at": "2025-04-13T14:45:00Z" },
    { "id": 23, "title": "API Authentication Failure", "description": "API failed to authenticate requests from external services, causing downtime.", "severity": "High", "reported_at": "2025-03-31T13:20:00Z" },
    { "id": 24, "title": "Broken Image on Homepage", "description": "A broken image was displayed on the homepage, affecting the visual presentation.", "severity": "Low", "reported_at": "2025-03-22T17:30:00Z" },
    { "id": 25, "title": "Error in User Registration", "description": "New users were unable to register due to a server-side error.", "severity": "High", "reported_at": "2025-04-02T11:15:00Z" },
    { "id": 26, "title": "Slow Database Queries", "description": "Database queries were taking longer than expected, leading to performance issues.", "severity": "Medium", "reported_at": "2025-03-18T08:30:00Z" },
    { "id": 27, "title": "Inconsistent User Data Display", "description": "User data appeared inconsistent across different pages of the app.", "severity": "Low", "reported_at": "2025-04-14T10:40:00Z" },
    { "id": 28, "title": "Poor Performance on Android Devices", "description": "App performance was poor on Android devices, with frequent crashes.", "severity": "High", "reported_at": "2025-03-23T13:00:00Z" },
    { "id": 29, "title": "Broken Form Validation", "description": "Form validation did not trigger correctly on certain fields.", "severity": "Low", "reported_at": "2025-03-27T14:50:00Z" },
    { "id": 30, "title": "Missing Content in Newsletter", "description": "Email newsletters were sent out without the proper content.", "severity": "Medium", "reported_at": "2025-03-24T16:00:00Z" },
    { "id": 31, "title": "Broken Search Functionality", "description": "Search bar failed to return relevant results, causing frustration.", "severity": "Medium", "reported_at": "2025-04-09T12:00:00Z" },
    { "id": 32, "title": "Non-Responsive Web Design", "description": "The website design was not responsive on mobile devices, affecting usability.", "severity": "Low", "reported_at": "2025-04-05T14:15:00Z" },
    { "id": 33, "title": "Privacy Policy Missing", "description": "The website did not display the privacy policy, violating legal requirements.", "severity": "High", "reported_at": "2025-04-03T09:00:00Z" },
]

export default list;